export interface descResponseItems{
    "id": number,
    "isin": string,
    "symbolTitle": string,
    "sectorTitle": string,
    "title": string,
    "summaryIntro": string,
    "fullIntro": "",
    "fundamentalSmartReview": "",
    "technicalSmartReview": "",
    "highlights": [],
    "affectingParameters": [],
    "finalComment": "",
    "minimumPrice": number,
    "maximumPrice": number,
    "minimumFairValue":number,
    "maximumFairValue": number,
    "minimumDividend": number,
    "maximumDividend": number,
    "averageDividend": number,
    "rate": number,
    "companySizeEnum": null,
    "companyTypeEnum": null,
    "companySizeTitle": "",
    "companyTypeTitle": "",
    "companySize": null,
    "companyType": null,
    "sectorCode": string,
    "companyIsin": string,
    "companyTitle": string,
    "symbolName": string 
}